# Writing figures and the generated tex. Nothing here decides anything; it only
# formats what the panels and the statistics already computed.

save_fig <- function(plot, name, width, height) {
  ggplot2::ggsave(file.path("figs", "out", paste0(name, ".pdf")), plot,
                  width = width, height = height, units = "in", device = cairo_pdf)
  invisible(NULL)
}

fmt <- function(x, digits = 2) formatC(x, format = "f", digits = digits)
pct <- function(x, digits = 1) formatC(100 * x, format = "f", digits = digits)
thousands <- function(x) format(x, big.mark = ",", trim = TRUE, scientific = FALSE)

macro <- function(name, value) sprintf("\\newcommand{\\%s}{%s}", name, value)

GENERATED_HEADER <- "% Generated by the figure script from hash-bound evidence. Do not hand-edit."

write_generated <- function(lines, name) {
  writeLines(c(GENERATED_HEADER, lines), file.path("tex", name))
  invisible(NULL)
}
